export const refs = {
  listContainer: document.querySelector('.list-card'),
  backdrop: document.querySelector('.backdrop'),
  pagination: document.querySelector('.tui-pagination'),
  homeBackground: document.querySelector('.page-header'),
  btnList: document.querySelector('.btn__list'),
  input: document.querySelector('.search-form'),
  homeLink: document.querySelector('.home-link'),
  libLink: document.querySelector('.lib-link'),
  watchedBtn: document.querySelector('.watched-btn'),
  queueBtn: document.querySelector('.queue-btn'),
  popularBtn: document.querySelector('.popular-btn'),
  topRatedBtn: document.querySelector('.top-rated-btn'),
  gallery: document.querySelector('.movies'),
  onLogo: document.querySelector('.logo'),
};
